import type { Metadata } from "next";
import "./globals.css";
import { ttNorms } from "@/utils/fonts";
import Header from "@/components/Header";
import Footer from "@/components/layout/Footer";
import Dropdown from "@/components/Dropdown";
import DropdownProvider from "@/providers/DropdownProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ttNorms.variable} antialiased`}>
        <DropdownProvider>
          <Dropdown />
          <Header />
        </DropdownProvider>
        {children}
        <Footer />
      </body>
    </html>
  );
}
